from enum import Enum


class Categoria(Enum):
    NO_RECONOCIDO = 0
    NATURAL = 1
    REAL = 2
    IDENTIFICADOR = 3
    PALABRA_RESERVADA = 4
    COMENTARIO_LINEA = 5
    COMENTARIO_BLOQUE = 6
    OPERADOR_ARITMETICO = 7
    OPERADOR_RELACIONAL = 8
    OPERADOR_LOGICO = 9
    OPERADOR_INCREMENTO = 10
    OPERADOR_DECREMENTO = 11
    COMENTARIO = 12
    ERROR_LEXICO = 13
    SEPARADOR = 14
    HEXADECIMAL = 15
    LLAVE_APERTURA = 16
    LLAVE_CIERRE = 17
    PARENTESIS_APERTURA = 18
    PARENTESIS_CIERRE = 19
    OPERADOR_ASIGNACION = 20
    CADENA_CARACTERES = 21
    TERMINAL = 22

    def __str__(self):
        return self.name
